### ISSUE TITLE
Extended search doesn't work when combining several search queries 

### ISSUE THREAD

**Issue by Pigeo** [Codepoints/Codepoints.net#103]
I'm trying to search all codepoints inside the "Common" script having the properties "Lowercase" AND "Changes When Uppercased (CWU)" both TRUE. [It gives me 8849 codepoints found](https://codepoints.net/search?q=&na=&int=&sc%5B%5D=Zyyy&Bidi_M=&Bidi_C=&CE=&Comp_Ex=&XO_NFC=&XO_NFD=&XO_NFKC=&XO_NFKD=&Join_C=&Upper=&Lower=1&OUpper=&OLower=&CI=&Cased=&CWCF=&CWCM=&CWL=&CWKCF=&CWT=&CWU=1&IDS=&OIDS=&XIDS=&IDC=&OIDC=&XIDC=&Pat_Syn=&Pat_WS=&Dash=&Hyphen=&QMark=&Term=&STerm=&Dia=&Ext=&SD=&Alpha=&OAlpha=&Math=&OMath=&Hex=&AHex=&DI=&ODI=&LOE=&WSpace=&Gr_Base=&Gr_Ext=&OGr_Ext=&Gr_Link=&Ideo=&UIdeo=&IDSB=&IDST=&Radical=&Dep=&VS=&NChar=) whereas a [simple search on the "Lowercase" property alone](https://codepoints.net/search?q=&na=&int=&Bidi_M=&Bidi_C=&CE=&Comp_Ex=&XO_NFC=&XO_NFD=&XO_NFKC=&XO_NFKD=&Join_C=&Upper=&Lower=1&OUpper=&OLower=&CI=&Cased=&CWCF=&CWCM=&CWL=&CWKCF=&CWT=&CWU=&IDS=&OIDS=&XIDS=&IDC=&OIDC=&XIDC=&Pat_Syn=&Pat_WS=&Dash=&Hyphen=&QMark=&Term=&STerm=&Dia=&Ext=&SD=&Alpha=&OAlpha=&Math=&OMath=&Hex=&AHex=&DI=&ODI=&LOE=&WSpace=&Gr_Base=&Gr_Ext=&OGr_Ext=&Gr_Link=&Ideo=&UIdeo=&IDSB=&IDST=&Radical=&Dep=&VS=&NChar=) gives only 2173 codepoints therefore I would expect to have less than 2173 in my extended search.
It seems that my 3 constraints (Script == Common ; Lowercase == true ; CWU == true) are combined using "OR" logical operators instead of "AND" logical operators as expected.

**Comment by Boldewyn** [comment]
This issue is still unresolved. I made some progress with the fulltext search, and most of the time it does the right thing. Unfortunately it seems like searching for scripts doesn’t work at all at the moment.

By the way: With the switch to the fulltext index you can indeed DIY a search query that matches your request, just not with a nice GUI, and with the need for a bit of insider knowledge: The search term `+Zyyy +prop_Lower_1 +prop_CWU_1` will match exactly the 27 characters with the given properties: https://codepoints.net/search?q=%2BZyyy+%2Bprop_Lower_1+%2Bprop_CWU_1

**Comment by Boldewyn** [comment]
By the way: Thank you very much for reporting it! (Although this thanks is coming almost six years too late :pensive: )

**Comment by Pigeo** [comment]
You're welcome, no problem! Better late than never 😂

**Comment by Boldewyn** [comment]
Fixed: https://codepoints.net/search?sc=Zyyy&Lower=1&CWU=1

That is, the search is still an `OR` search, and the query results in ~10,000 matches. But the 27 code points that match all terms are the very first ones.

If I can figure out a user-friendly way to switch between `AND` and `OR` searches, I’ll add that to the search UI. But since it is already somewhat cluttered (due to the large number of possible parameters), I’m hesitant to just slap another checkbox in there.
