### ISSUE TITLE
[Enhancement] Use vector color font for emoji glyphs

### ISSUE THREAD

**Issue by drott** [Codepoints/Codepoints.net#121]
Nice to see the Noto emoji glyphs embedded for showing emoji.
From the source of the page I see these are embedded as SVG with JS logic to copy the codepoint to the clipboard when clicking. 

As vector color fonts are available in modern browsers, perhaps displaying the emoji as a COLRv1, COLRv0 or - for fallback - as an SVG fonts' glyphs may be a good option.

Compare: https://fonts.google.com/noto/specimen/Noto+Color+Emoji

**Comment by Boldewyn** [comment]
This was actually the old implementation until last November. I decided against it for several reasons. The most prominent is, that I want to animate CJK glyphs (which would actually already work, if https://bugzilla.mozilla.org/show_bug.cgi?id=1779834 and https://bugs.chromium.org/p/chromium/issues/detail?id=1345231 would’ve been fixed by browser vendors).

Apart from that it would be harder for me to create a font on the fly, while currently I’ve got the SVG shapes sitting as nice little strings in the DB waiting to be merged together when a bunch of codepoints should be shown. (And by the way, SVG shapes from different fonts, not only Noto. Most of the newest shapes are still from GNU Unifont, since they are most of the time the fastest to update.)

This is all in all a tricky area. I’ve played with a lot of ideas, mainly out of the need to not self-DDoS me when a block page renders 500 code point images. I agree that using a web font would be a nice idea (as I said, that was indeed my implementation from back in 2012), but it’s got some tricky parts with it, too. But thanks for the suggestion, and if I’ll re-work the representation at some time this will definitively be on the list of options again!

**Comment by Boldewyn** [comment]
By the way, if [this specification](https://www.w3.org/TR/IFT/) gains traction it might well be, that a web-font-based solution comes back as best-of-class solution.

**Comment by drott** [comment]
Thanks for sharing the details and considerations. Perhaps one note: Before IFT becomes a reality, custom subsetting based on [hb-subset](https://harfbuzz.github.io/harfbuzz-hb-subset.html) (also exists as command line tool) or fonttools' [pyftsubset](https://fonttools.readthedocs.io/en/latest/subset/index.html) as a build process step to build static resources or as dynamic server side service could be an option if you have a known fixed amount of glyphs per page.
