### ISSUE TITLE
Support Unicode 16

### ISSUE THREAD

**Issue by xfq** [Codepoints/Codepoints.net#134]
Are there any plans to support Unicode 16 in the near future?

**Comment by Boldewyn** [comment]
Yes. Indeed, I’m almost ready since commit 3a40fbc960cdcec578ab0e624a6deefc0295ce4b, and the data is finished.

The only thing holding back the update is me trying to find a 3 to 4 hour window where I can run the update and care for any problems that might appear.

Sorry for the wait! Unfortunately, there is always a lot of manual work involved for an update (one reason are new properties in the Unicode standard that need to be addressed).

On the bright side, the update will also support the new Unikemet data for hieroglyphs.

**Comment by Boldewyn** [comment]
I updated the database the other minute. We’re now running with full Unicode 16.0 support: https://codepoints.net/search?age=16.0 . Thanks for the patience!
