### ISSUE TITLE
Searching for "l with stroke" does not retrieve U+0142 

### ISSUE THREAD

**Issue by jsbien** [Codepoints/Codepoints.net#75]
I get "No Codepoints Found".

**Comment by Boldewyn** [comment]
Hm, that is strange. When I try, it finds many characters, U+0142 being one of the first. There is no problem in the error logs. I'll dig deeper, perhaps something with MySQL query timeouts.

**Comment by jsbien** [comment]
Today from a different computer it works also for me. I will check it again in the evening and close the issue if unable to reproduce.

**Comment by jsbien** [comment]
I know this shouldn't happen, but the search works differently from my
office and home computers, both running Debian, but slightly different
versions.

I was too quick reporting that "l with stroke" just works. In the office
the name search works, but gives the same results as free search, which
is not correct.

At home free search is OK, name search yields "No Codepoints Found".

**Comment by Boldewyn** [comment]
Can confirm, that the name search is broken, if a space is present.

Problem: SearchComposer doesn't split in several queries on space, then SearchResult adds a query `term LIKE 'name with spaces'`. With the new search index there is no such row anymore, unfortunately, because names are already split in the table.

Fix: Either let SearchComposer split on space in several sub-queries (a) or let SearchResult join the `codepoints` table and query for full name (b).

(a) will find many characters ('LATIN CAPITAL LETTER E' finds all characters with 'LATIN', 'CAPITAL', ... in the name), potentially too many. (b) will find only absolute matches ("Was it 'LATIN CAPITAL' or 'CAPITAL LATIN'?").

I'll think a bit about which solution might be the better. I tend to (b), because you can simulate (a) with the free text search already.

**Comment by jsbien** [comment]
Personally I would prefer the name search to be as compatible with FileFormat as possible.

**Comment by Boldewyn** [comment]
I see. Yes, that looks like a good middle path.
