### ISSUE TITLE
make ucd.sqlite fails

### ISSUE THREAD

**Issue by jsbien** [Codepoints/Codepoints.net#76]
Probably a stupid mistake of mine, I've got

make: *** No rule to make target 'tools/fonts/target/sql/*.sql', needed by 'ucd.sqlite'.  Stop.

Regards

Janusz

**Comment by Boldewyn** [comment]
Oh, that's a remnant from the times, where the site was powered by SQLite. I've switched to MySQL last fall and forgot to change the Makefile.

You can fetch the [latest database dump](https://dumps.codepoints.net/latest.sql.gz) from dumps.codepoints.net and import it in a local database. Then create a file `db.conf` one folder above the `index.php` file with the content:

    [clientreadonly]
    password=*database password*
    user=*database user*
    database=*database name*

That should do it and you should have a running local clone.

Todo for me: Fix the Makefile.

**Comment by jsbien** [comment]
On Thu, Feb 18 2016 at 23:25 CET, notifications@github.com writes:
> Oh, that's a remnant from the times, where the site was powered by
> SQLite. I've switched to MySQL last fall and forgot to change the
> Makefile.
>
> You can fetch the latest database dump from dumps.codepoints.net and
> import it in a local database. Then create a file db.conf one folder
> above the index.php file with the content:
>
> [clientreadonly]
> password=*database password*
> user=*database user*
> database=*database name*
>
> That should do it and you should have a running local clone.
>
> Todo for me: Fix the Makefile.

Thanks for explanation. I will test it some time later.

**Comment by jsbien** [comment]
Unfortunately there are some problems.

[logs.zip](https://github.com/Codepoints/Codepoints.net/files/139034/logs.zip)

**Comment by Boldewyn** [comment]
I'm in the middle of moving away from my current Javascript build tool. (Unfortunately since July '15, because it's a somewhat difficult endeavour in Javascript land right now.)

You can, however, run a local codepoints.net clone directly with a checked out git version. The `npm` calls in the Makefile would only be necessary, if you want to modify CSS or JS code.

Otherwise I expect these problems to vanish as soon as I fix #52.

From looking at the logs, it might also be, that there are problems with your installation of `npm`. You could try `npm --version`, `node --version` and a `npm install jquery` in your computer's `/tmp` folder, to see if there is any problem.

**Comment by jsbien** [comment]
On Sun, Feb 21 2016 at 22:08 CET, notifications@github.com writes:
> I'm in the middle of moving away from my current Javascript build
> tool. (Unfortunately since July '15, because it's a somewhat difficult
> endeavour in Javascript land right now.)
>
> You can, however, run a local codepoints.net clone directly with a
> checked out git version.

Sorry for a naive question, but how to access it?

> The npm calls in the Makefile would only be
> necessary, if you want to modify CSS or JS code.
>
> Otherwise I expect these problems to vanish as soon as I fix #52.
>
> From looking at the logs, it might also be, that there are problems
> with your installation of npm.

It installed from a Debian package.

> You could try npm --version, node -
> -version

jsbien@VivoPC-D8:~$ npm --version
1.4.21
jsbien@VivoPC-D8:~$ node --version
bash: node: command not found

Any suggestion?

**Comment by Boldewyn** [comment]
> Sorry for a naive question, but how to access it?

What I meant was, that when you check out this repository (either with `git clone ...` or by downloading from Github), set up a database and create a [`db.conf`](https://github.com/Codepoints/Codepoints.net/blob/master/Makefile#L98-L108) file, the code should be ready to run.

In order to get it running on your local machine, you also need a web server, that can interpret the browser requests. If you meant that, I can point you to how to configure Apache to do this (it's rather quick to set up). Just drop me a line!

> jsbien@VivoPC-D8:~$ npm --version 1.4.21
> jsbien@VivoPC-D8:~$ node --version
> bash: node: command not found
>
> Any suggestion?

This is strange! On Ubuntu (and I'm quite confident on Debian, too), the `npm` package depends on `nodejs`, which should install the `node` command on your system. You could try

> apt-get install --reinstall nodejs

That should provide you with the `node` command. But as I said, you'd only need this for making changes to the CSS stylesheets or Javascript files, not for running the system.

**Comment by jsbien** [comment]
On Tue, Feb 23 2016 at 21:01 CET, notifications@github.com writes:

[...]

> In order to get it running on your local machine, you also need a web
> server, that can interpret the browser requests. If you meant that,

Yes, that's what I mean. I have Apache already installed,

> I
> can point you to how to configure Apache to do this (it's rather quick
> to set up). Just drop me a line!

What about including the instruction in the Readme file?

>
>     jsbien@VivoPC-D8:~$ npm --version 1.4.21
>     jsbien@VivoPC-D8:~$ node --version
>     bash: node: command not found
>
>     Any suggestion?
>
> This is strange! On Ubuntu (and I'm quite confident on Debian, too),
> the npm package depends on nodejs, which should install the node
> command on your system.

The Debian package for nodejs has been automatically installed, but it
contains the 'nodejs' command, not 'node'.

> You could try
>
>     apt-get install --reinstall nodejs
>
> That should provide you with the node command. But as I said, you'd
> only need this for making changes to the CSS stylesheets or Javascript
> files, not for running the system.

I have neither qualification nor motivation to change them, but I would
like to solve the problem just of curiosity.

**Comment by Boldewyn** [comment]
Since version 5.4, PHP includes its own small development web server. I just played around with it a bit. When you pull the current master branch,

    your-clone $ git checkout master
    your-clone $ git pull

you get a new file `devrouter.php`. This allows you to call (in the folder, where the `README.md` file is):

    your-clone $ php -S localhost:8000 -t codepoints.net devrouter.php

Then you can browse the local copy at [`localhost:8000`](http://localhost:8000/). There are some rough edges and 404 Not Found errors, but it's a quick 'n dirty way to get the site up for testing. I put this info in the README right now.

----

If you want the "true thing", an Apache configuration could look like this:

1. Choose a domain name, e.g., `codepoints.localhost`. Then place this line in `/etc/hosts`:

        127.0.0.1 codepoints.localhost

2. Add a file `/etc/apache2/sites-available/codepoints.conf` with this content:

    ```apache
    <VirtualHost *:80>
        # where you checked out the code + "codepoints.net" at the end
        DocumentRoot "/var/www/codepoints.net/codepoints.net"
        # the name you put in the hosts file
        ServerName codepoints.localhost
        # the same directory as in DocumentRoot above:
        <Directory /var/www/codepoints.net/codepoints.net/>
            Options Indexes FollowSymLinks
            AllowOverride All
            Require all granted
        </Directory>
    </VirtualHost>
    ```

3. Link this file in the `sites-enabled` folder:

    ```bash
    cd /etc/apaches/sites-enabled
    ln -s ../sites-available/codepoints.conf
    ```

3. Restart Apache: `sudo service apache2 restart`

4. Then you can access the site under [`codepoints.localhost`](http://codepoints.localhost).

-----

Getting the `node` command: It seems, that [Debian and some Ubuntus](http://stackoverflow.com/questions/18130164/nodejs-vs-node-on-ubuntu-12-04) chose to name the executable `nodejs`. You can symlink this to `node`:

    sudo ln -s /usr/bin/nodejs /usr/local/bin/node

This should fix the issue. However, if you made it this far, the commands may _still_ fail, because the nodejs packages distributed are fairly old. Installing a newer node.js is, to say the least, [a bit complicated](https://github.com/nodejs/node-v0.x-archive/wiki/Installing-Node.js-via-package-manager).

**Comment by jsbien** [comment]
On Tue, Feb 23 2016 at 21:57 CET, notifications@github.com writes:
> Since version 5.4, PHP includes its own small development web server.
> I just played around with it a bit. When you pull the current master
> branch,
>
> your-clone $ git checkout master
> your-clone $ git pull
>
> you get a new file devrouter.php. This allows you to call (in the
> folder, where the README.md file is):
>
> your-clone $ php -S localhost:8000 -t codepoints.net devrouter.php
>
> Then you can browse the local copy at localhost:8000. There are some
> rough edges and 404 Not Found errors, but it's a quick 'n dirty way to
> get the site up for testing. I put this info in the README right now.


Thanks, it works.

>
> ----------------------------------------------------------------------
>
> If you want the "true thing", an Apache configuration could look like
> this:

[...]

> 5   Then you can access the site under codepoints.localhost.

Iy also works. An unobvious thing was the need to do a2enmod rewrite.

>
> ----------------------------------------------------------------------
>
> Getting the node command: It seems, that Debian and some Ubuntus chose
> to name the executable nodejs. You can symlink this to node:
>
> sudo ln -s /usr/bin/nodejs /usr/local/bin/node

I've got to the point of

casperjs: command not found

I undestand Caspers JS is not packaged for Debian and is to be installed
from the source.

I think I'll give up at this moment and the issue may be closed.

Thanks again.

Regards

Janusz

**Comment by jsbien** [comment]
I'm going to use Apache, but just of curiosity: can I have both devrouter.php from the master branch and the Polish translation from the pl branch?

**Comment by Boldewyn** [comment]
I'll merge the master branch into `pl` soon, then it's in there, too. It should work as advertized in the README.

If you don't want to wait so long, you can download it from Github and just place it there. (In this case, git will print an error, when you update your `pl` branch after I merged the master branch in it. Then simply delete the file again.)

**Comment by Boldewyn** [comment]
The Makefile is now cleared of the old cruft. I also merged master into the pl branch. Small remark: You'll need a relatively new node.js version, otherwise something will complain, and [`composer`](https://getcomposer.org/download/). Then a simple `make` should run through smoothly.
