### ISSUE TITLE
For emoji, use an emoji-specific font family

### ISSUE THREAD

**Issue by indrora** [Codepoints/Codepoints.net#98]
A slight nitpick in the grand scheme of things, but shouldn't Emoji attempt to use a local (machine-local) typeface that matches them?

For instance, here's U+1F47B (GHOST):

![image](https://cloud.githubusercontent.com/assets/470584/18222583/3525193e-7159-11e6-8d42-5dcf3f0fcd94.png)

A fair representation. However, I have a typeface for that, `Segoe UI Emoji`. Here's U+1F47B when rendered using it:

![image](https://cloud.githubusercontent.com/assets/470584/18222597/9c81c7b2-7159-11e6-88bc-09acfbaec36b.png)

Yup, there's some issues with it. However, which is more important: Accurate representation or pretty?

**Comment by indrora** [comment]
Bump?

**Comment by Boldewyn** [comment]
Thanks for the report! Emojis are a tricky territory. And I'd love to display more info about them, but time constraints are currently a serious issue for me. (Just look at the last commit here, _sigh_.)

What I do want to do at least is, to add a link to the Emojipedia for them. Also, I'll most likely use the Noto Monocolor Emoji font for emojis in the future for consistency.

Why not colored or platform-dependent? Well, look at http://emojipedia.org/ghost/. Which one should I choose? Most of them come bundled in some sort of font. And for some emojis there are significant differences in the single vendor renderings. (Google for "gun emoji" to get an idea...)

OK, just do nothing then? Platform-dependent has its own set of problems. Not all emojis are supported on all platforms. Someone with an Android 4 smartphone won't see the Unicode 9 emojis but some nasty Unicode fallback thingy. Linux users might be lucky or not, but there's no way for me as developer to detect that. What dimension does the emoji render exactly? :(

The page at codepoints.net is intended to give in-depth information about the universally valid technical properties of a code point. Therefore I'd rather not get into platform-specific problems. (To phrase it in your words, I'm choosing "accurate" in the sense of "something universally valid" over "pretty" in the context of this site.)

That'd be a good time to get the link to Emojipedia up and running, though, because this site provides exactly the counterpart information.
